### ISSUE TITLE
  import pillow_avif  # noqa: F401 # imported for side effects ModuleNotFoundError: No module named 'pillow_avif'

### ISSUE THREAD

**Issue by hejianbo1994** [thewhiterabbit/Deploy_Saleor#10]

**Comment by Youssefbenhammouda** [comment]
Same here

**Comment by ars3nicum** [comment]
same

**Comment by rtecomdev** [comment]
Same here, here is the traceback (I tried to install Pillow manually with pip before the setup but it keeps getting the same error):

Traceback (most recent call last):
  File "/home/contact/saleor/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/core/management/base.py", line 425, in run_from_argv
    connections.close_all()
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/utils/connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/utils/connection.py", line 76, in all
    return [
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/db/utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/contact/env/saleor/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/contact/saleor/saleor/__init__.py", line 1, in <module>
    import pillow_avif  # noqa: F401 # imported for side effects
ModuleNotFoundError: No module named 'pillow_avif'

**Comment by flytoo2016** [comment]
same probleme
