### ISSUE TITLE
npm ERR! notarget No matching version found for npm@next.

### ISSUE THREAD

**Issue by bastienallain** [thewhiterabbit/Deploy_Saleor#4]
Hello fresh install on Ubuntu 20.04 (LTS) x64 any idea Thanks

```
Creating production deployment packages for Saleor API & GraphQL...

npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-16T04_19_33_410Z-debug.log
root@ubuntu-s-2vcpu-4gb-amd-lon1-01:~# cat /root/.npm/_logs/2022-12-16T04_19_33_410Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'npm@next' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose npm-session e95e883838cea95f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/npm 130ms
8 silly fetchPackageMetaData error for npm@next No matching version found for npm@next.
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 220ms
11 verbose type tag
12 verbose stack npm: No matching version found for npm@next.
12 verbose stack     at pickManifest (/usr/share/npm/node_modules/npm-pick-manifest/index.js:122:13)
12 verbose stack     at fetchPackument.then.packument (/usr/share/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14)
12 verbose stack     at tryCatcher (/usr/lib/nodejs/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/nodejs/bluebird/js/release/promise.js:512:31)
12 verbose stack     at Promise._settlePromise (/usr/lib/nodejs/bluebird/js/release/promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (/usr/lib/nodejs/bluebird/js/release/promise.js:614:10)
12 verbose stack     at Promise._settlePromises (/usr/lib/nodejs/bluebird/js/release/promise.js:693:18)
12 verbose stack     at Async._drainQueue (/usr/lib/nodejs/bluebird/js/release/async.js:133:16)
12 verbose stack     at Async._drainQueues (/usr/lib/nodejs/bluebird/js/release/async.js:143:10)
12 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/nodejs/bluebird/js/release/async.js:17:14)
12 verbose stack     at runCallback (timers.js:705:18)
12 verbose stack     at tryOnImmediate (timers.js:676:5)
12 verbose stack     at processImmediate (timers.js:658:5)
13 verbose cwd /root/saleor
14 verbose Linux 5.4.0-122-generic
15 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "npm@next"
16 verbose node v10.19.0
17 verbose npm  v6.14.4
18 error code ETARGET
19 error notarget No matching version found for npm@next.
20 error notarget In most cases you or one of your dependencies are requesting
20 error notarget a package version that doesn't exist.
21 verbose exit [ 1, true ]
root@ubuntu-s-2vcpu-4gb-amd-lon1-01:~# npm -v
6.14.4
root@ubuntu-s-2vcpu-4gb-amd-lon1-01:~# npm install -g npm@next
npm ERR! code ETARGET
npm ERR! notarget No matching version found for npm@next.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

```

**Comment by alta-atc** [comment]
Same issue for me.

**Comment by alta-atc** [comment]
I have submitted a pull request with a fix.

**Comment by alta-atc** [comment]
This issue can now be closed.

**Comment by thewhiterabbit** [comment]
Thank you, @vivacoda for the report, and @alta-atc for the commit. Closing.
